baseURL = "https://galvarado.com.mx/"
languageCode = "es-es"
title = "Guillermo Alvarado"
theme = "mediumish-gohugo-theme"
summaryLength = 30
copyright = "Guillermo Alvarado - Todos los derechos reservados"
enableEmoji = true
disqusShortname = "galvarado-com-mx"
googleAnalytics = "UA-118969871-1"
comments = true

[params]
  logo = "/images/profile.png"
  description ="Bienvenido a mi blog personal. Aquí encontrarás las experiencias de un desarrollador que migró al mundo de la infraestructura. Escribo de mi experiencia en Cloud, Containers, DevOps, Entrega continua, Microservicios, Desarrollo... "
  mailchimp = "https://galvarado.us19.list-manage.com/subscribe/post?u=7ca0350f86d9576b40bfe7cee&amp;id=0649daac95"
  mailprotect = "b_7ca0350f86d9576b40bfe7cee_0649daac95"

[params.author]
  name = "Guillermo Alvarado"
  thumbnail = "images/profile.png"
  description = "Creador del blog"

[params.index]
  picture = "/images/logo.png"
  title = "Hola Memo"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "galvarado"
  linkedin = "guillermoalvarado89"
  twitter = "galvarado89"

## Main Menu
[[menu.main]]
    name = "Inicio"
    weight = 100
    identifier = "index"
    url = "/"
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 200
    url = "/static/blog"
[[menu.main]]
    name = "Acerca de"
    identifier = "about"
    weight = 200
    url = "/static/about"
  [[menu.main]]
    name = "Contacto"
    identifier = "contact"
    weight = 200
    url = "/static/contact"